---
title: "Matching"
author: "Derrick Yam & Michael Lopez"
date: "December, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Required libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(dplyr)
library(splines)
library(ggplot2)
library(RColorBrewer)
library(Matching)
library(gtools)
set.seed(100)
```

## Read in data

```{r}
NFL <- read_csv("Data/NFL_fourthdown_cleaned.csv")
sample_n(NFL, 1)
#Create an averaged win probability
NFL <- mutate(NFL, wp.ave = (wp.Lock + wp.Scrapr)/2)
```

## Point differential imbalance

```{r}
pd <- ggplot(NFL, aes(x = ptsdiff)) + 
  geom_density(position = "identity", alpha = 0.5, aes(fill = as.factor(Attempt.4))) + 
  scale_fill_brewer(type = "qual", palette = "Dark2") + 
  ggtitle("Point differential before fourth down plays") + 
  xlab("Point Differential") + ylab("Density") +
  xlim(-40, 35) + 
  annotate("text", -23, .025, label = "Went for it", colour = "#d95f02", alpha = 1, size = 4) + 
  annotate("text", 12, .05, label = "Did not go for it", colour = "#1b9e77", alpha = 1, size = 4) + 
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.2)),
        legend.position = "none",
        axis.title.y = element_text(size = rel(1.2)),
        axis.title.x = element_text(size = rel(1.2)),
        axis.text.y = element_blank())
pd

#ggsave(file = "Figures/Point_Differential_Imbalance.png", plot = pd, height = 5, width = 6)
```


## Propensity score model

```{r}
ps.L1 <- glm(Attempt.4 ~ ns(yfog, 10) * ns(ytg, 5) + ns(yfog, 10) * ns(time, 4) + ns(yfog, 10) * pointdiff + 
               ns(ytg, 5) * ns(time, 4) + ns(ytg, 5) * pointdiff + ns(time, 4)* pointdiff + ns(yfog, 10) +  
               ns(ytg, 5) + ns(time, 4) + pointdiff + cond.cat + ns(temp, 5) + ns(humd, 5) + ns(wspd, 5) + 
               ns(sprv,5) + ns(ou, 5) + ns(OR.pass,5) + ns(OR.rush, 5) + ns(DR.pass, 5) + ns(DR.rush,5) + 
               ns(wk, 4) + Home + ns(wp.ave, 10), data = NFL, family = "binomial")


NFL$predict.fitms <- predict(ps.L1, NFL, type = "response")

## Sanity check -- what do PSs look like?
pmspl <- ggplot(NFL, aes(x = predict.fitms, group = Attempt.4, colour = Attempt.4)) 
pmspl + geom_histogram(position = "identity") + facet_wrap(~Attempt.4) + scale_y_continuous(lim = c(0, 700))
```

## Filter for the common support interval

```{r}
limits <- NFL %>% 
  filter(coaches.should == "Go for it") %>% 
  group_by(Attempt.4) %>% 
  summarise(min.score = min(predict.fitms), max.score = max(predict.fitms))

low.bound <- min(limits$max.score)
upper.bound <- max(limits$min.score)

NFL.common.support <- NFL %>% 
  filter(predict.fitms <= low.bound, predict.fitms >= upper.bound)
```

## Recalculate propensity scores on common support

```{r}
ps.L2 <- glm(Attempt.4 ~ ns(yfog, 10) * ns(ytg, 5) + ns(yfog, 10) * ns(time, 4) + ns(yfog, 10) * pointdiff + 
               ns(ytg, 5) * ns(time, 4) + ns(ytg, 5) * pointdiff + ns(time, 4)* pointdiff + ns(yfog, 10) +  
               ns(ytg, 5) + ns(time, 4) + pointdiff + cond.cat + ns(temp, 5) + ns(humd, 5) + ns(wspd, 5) + 
               ns(sprv,5) + ns(ou, 5) + ns(OR.pass,5) + ns(OR.rush, 5) + ns(DR.pass, 5) + ns(DR.rush,5) + 
               ns(wk, 4) + Home + ns(wp.ave, 10), data = NFL.common.support, family = "binomial")


NFL.common.support$predict.fitms2 <- predict(ps.L2, NFL.common.support, type = "response")

## Range where teams should go for it
NFL.gfi <- NFL.common.support %>% 
  filter(coaches.should == "Go for it")

#write.csv(NFL.gfi, "Data/NFL.gfi.csv") ## This is saved to re-use later
```

## Match for ATC Random Forest WP Model

```{r}
NFL.gfi %>% 
  summarise(mean = mean(seconds), sd = sd(seconds)) %>% 
  summarise(caliper = 450/sd) #Calculate the caliper size for plays within half of a quarter (450 seconds)

#Create the covariate matching matrix
psm <- NFL.gfi %>% dplyr::select(pid, predict.fitms2, wp.ave, ytg, seconds)
X <- psm[,2:5]
X[,1:2] <- gtools::logit(X[,1:2])

match.atc <- Match(Y = NULL,
                estimand = "ATC",
                Tr = as.numeric(NFL.gfi$Attempt.4),
                M = 1, 
                ties = FALSE,
                X = X,
                calip=c(0.5, 0.5, 0, .432), 
                replace=T, Weight = 1)

summary(match.atc)

pairs.atc <- cbind(match.atc$index.treated, match.atc$index.control)
dim(pairs.atc)


## treated and control data sets
treated.atc <- NFL.gfi[match.atc$index.treated,]
control.atc <- NFL.gfi[match.atc$index.control,]

#Define the paired id which is the row number from NFL.GFI dataset
treated.atc <- cbind(treated.atc, pairs.atc[,2])
colnames(treated.atc)[colnames(treated.atc)== "pairs.atc[, 2]"] <- "paired.id"

control.atc <- cbind(control.atc, pairs.atc[,1])
colnames(control.atc)[colnames(control.atc)== "pairs.atc[, 1]"] <- "paired.id"

#Define the matched pair for the team plot
control.atc$off.pair <- control.atc$off
treated.atc$off.pair <- control.atc$off


matched.subset.atc <- rbind(control.atc, treated.atc)

#write.csv(matched.subset.atc, file = "Data/matched.subset.atc.csv", row.names = FALSE)
```

```{r}
#Review of univariate balance
pd2 <- ggplot(matched.subset.atc, aes(x = ptsdiff)) + 
  geom_density(position = "identity", alpha = 0.5, aes(fill = as.factor(Attempt.4))) + 
  scale_fill_brewer(type = "qual", palette = "Dark2") + 
  ggtitle("Point differential before fourth down plays, after matching") + 
  xlab("Point Differential") + ylab("Density") +
  theme(legend.position = "none") + 
  xlim(-40, 35) + 
  annotate("text", -23, .025, label = "Went for it", colour = "#d95f02", alpha = 1, size = 4) + 
  annotate("text", 12, .05, label = "Did not go for it", colour = "#1b9e77", alpha = 1, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.2)),
        legend.position = "none",
        axis.title.y = element_text(size = rel(1.2)),
        axis.title.x = element_text(size = rel(1.2)),
        axis.text.y = element_blank())
pd2

#ggsave(file = "Figures/Point_Differential_ATC.png", plot = pd2, width = 6, height = 5.5)


```


## Love plot for matching effectiveness

```{r}
## Variables 
vars <- c("yfog", "ytg", "time", "pointdiff", "wspd", "cond.cat", "temp", "humd", "sprv", "ou", "OR.pass", "OR.rush", "DR.pass", "DR.rush", "wk", "wp.ave", "Home")

levels(NFL.gfi$cond.cat) <- c("Dome", "Dry", "Precipitation")

##Calculate the standardized bias of the Initial data
NFL.gfi.love <- NFL.gfi[,vars]
NFL.gfi.love <- data.frame(model.matrix(~.-1, data = NFL.gfi.love))

NFL.gfi.love$cond.catDome <- 1 - (NFL.gfi.love$cond.catDry + NFL.gfi.love$cond.catPrecipitation)

NFL.gfi.love$Attempt.4 <- NFL.gfi$Attempt.4
NFL.gfi.gather <- gather(NFL.gfi.love, "variable", "metric", yfog:cond.catDome) 
NFL.gfi.gather <- NFL.gfi.gather %>%  
  dplyr::select(Attempt.4, variable, metric)

pre.match <- NFL.gfi.gather %>% 
  group_by(variable) %>%
  summarise(ave.treatment = sum(metric*Attempt.4)/sum(Attempt.4), 
            ave.control =   sum(metric*(1-Attempt.4))/sum(1-Attempt.4), 
            sd.control = sd(metric), 
            bias = (ave.treatment - ave.control)/sd.control)%>% 
  mutate(type = "pre-matched")%>% 
  dplyr::select(variable, bias, type)
  
##Calculate the standardized bias of the Matched data
levels(matched.subset.atc$cond.cat) <- c("Dome", "Dry", "Precipitation")

matched.subset.atc.love <- matched.subset.atc[,vars]
matched.subset.atc.love <- data.frame(model.matrix(~.-1, data = matched.subset.atc.love))
matched.subset.atc.love$cond.catDome <- 1 - (matched.subset.atc.love$cond.catDry +
                                               matched.subset.atc.love$cond.catPrecipitation)



matched.subset.atc.love$Attempt.4 <- matched.subset.atc$Attempt.4
matched.subset.atc.gather <- gather(matched.subset.atc.love, "variable", "metric", yfog:cond.catDome) 
matched.subset.atc.gather <- matched.subset.atc.gather %>%  
  dplyr::select(Attempt.4, variable, metric)

post.match <- matched.subset.atc.gather %>% 
  group_by(variable) %>%
  summarise(ave.treatment = sum(metric*Attempt.4)/sum(Attempt.4), 
            ave.control =   sum(metric*(1-Attempt.4))/sum(1-Attempt.4), 
            sd.control = sd(metric), 
            bias = (ave.treatment - ave.control)/sd.control) %>% 
  mutate(type = "post-matched") %>% 
  dplyr::select(variable, bias, type)

#Combine the data frames for the love plot
love.plot <- bind_rows(pre.match, post.match)

##Rename some of the variable names for the plot
love.plot$variable <- as.character(love.plot$variable)
love.plot$variable[love.plot$variable == "cond.catDome"] <- "condcatDome"
love.plot$variable[love.plot$variable == "cond.catDry"] <- "condcatDry"
love.plot$variable[love.plot$variable == "cond.catPrecipitation"] <- "condcatPrecip"
love.plot$variable[love.plot$variable == "pointdiffpdiff.M1"] <- "pointdiff.M1"
love.plot$variable[love.plot$variable == "pointdiffpdiff.M2"] <- "pointdiff.M2"
love.plot$variable[love.plot$variable == "pointdiffpdiff.M3"] <- "pointdiff.M3"
love.plot$variable[love.plot$variable == "pointdiffpdiff.M4"] <- "pointdiff.M4"
love.plot$variable[love.plot$variable == "pointdiffpdiff.P1"] <- "pointdiff.P1"
love.plot$variable[love.plot$variable == "pointdiffpdiff.P2"] <- "pointdiff.P2"
love.plot$variable[love.plot$variable == "pointdiffpdiff.P3"] <- "pointdiff.P3"
love.plot$variable[love.plot$variable == "pointdiffpdiff.P4"] <- "pointdiff.P4"
love.plot$variable[love.plot$variable == "pointdiffpdiff.T"] <- "pointdiff.T"

love.plot$variable <- factor(love.plot$variable, levels = sort(unique(love.plot$variable), decreasing = TRUE))


love <- love.plot %>% 
  ggplot(aes(variable, bias, shape = type)) + geom_point() +
  geom_hline(yintercept = -0.2, lty = 2) +
  geom_hline(yintercept = 0.2, lty = 2) +
  coord_flip() + 
    scale_shape_manual(values = c(16, 21), "Data cohort") + ylab("Standardized bias") + xlab("Variable") + 
  ggtitle("Standardized bias, before and after matching") +
  theme(plot.title = element_text(hjust = 0.5, size = rel(1.2)),
        axis.title.y = element_text(size = rel(1.2)),
        axis.title.x = element_text(size = rel(1.2)))
love

#ggsave(file = "Figures/Love_Plot_ATC.png", plot = love, height = 6, width = 5.5)

```

